### ISSUE TITLE
Incorrect line numbers in compile errors due to rst_prolog

### ISSUE THREAD

**Issue by atilantera** [apluslms/compile-rst#1]
It would be nice to update Sphinx to this container for usability. Current version 1.6.7 has a [line number bug](https://github.com/sphinx-doc/sphinx/issues/7045) which has been corrected in later versions. I and Ari have encountered this a couple of times. It degrades usability, as one cannot trust the line numbers when tracking a compilation error due to a typo.

**Comment by raphendyr** [comment]
Challenge is that updating Sphinx on mooc-grader servers is hard. If any old courses break because of the update, then that update can't be done. It would be required to verify that every course compiles identically with a newer Sphinx before the package can be updated on the server. This container (specifically tag 1.6) includes the same version of the Sphinx as in the server, so the container and the server would produce the same build.

Tha plan was that the mooc-grader wouldn't build courses anymore. Instead, courses would be build using the container. Thus, the Sphinx could be updated per course and so there wouldn't be problems described above.

However, it could be possible that the Sphinx in the server could be updated to 1.8.5 (latest 1.x as of writing), without problems. It could be a good idea to investigate that, assuming that the Shepherd project is not progressing.

It's good to note that Sphinx 2.0 removes some APIs that were deprecated in 1.7, so it's likely that the version can't be updated to 2.x, 3.x or 4.x.

**Comment by markkuriekkinen** [comment]
Like raphendyr said, the Sphinx version in the server has not been upgraded due to backwards-compatibility. The server could only be upgraded in the summer so that courses have enough time to adapt to the changes. I would not worry about compatibility in very old courses since they are usually hidden from students anyway, but we must not break current courses without a proper warning beforehand.

**Comment by atilantera** [comment]
I see. From an outsider's view one solution could be make mooc-grader run the same compile-rst container, or even have containers tagged with different versions of Sphinx, but I don't know more. Besides, upgrading Sphinx might need upgrading [A+ RST tools](https://github.com/apluslms/a-plus-rst-tools), if the API of Sphinx has been changed.

**Comment by raphendyr** [comment]
> one solution could be make mooc-grader run the same compile-rst container, or even have containers tagged with different versions of Sphinx

Yes, that is the purpose of Shepherd. My initial upgrade plan was to make mooc-grader use `roman`. I did some work to support existing courses in containers without any changes (see [script mimicing mooc-grader build process](https://github.com/apluslms/compile-rst/blob/1.6-1.0/rootfs/usr/local/bin/mooc-grader-build)). However, there are lot of problems with that plan too, which is the reason I didn't push for that before. You can also check this [a PR in mooc-grader](https://github.com/apluslms/mooc-grader/pull/36), which tried to implement this.

**Comment by markkuriekkinen** [comment]
The image (in Docker Hub) `apluslms/compile-rst:4.1` has Sphinx v4.1 installed. A-plus-rst-tools v1.4 supports Sphinx v4.1. Closing this issue as completed.
